persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# Standard MQTT Listener
listener 1883
allow_anonymous false
password_file /mosquitto/config/password.txt

# Websocket Listener (for Nginx Proxy)
listener 9001
protocol websockets
allow_anonymous false
password_file /mosquitto/config/password.txt