version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config:rw
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    deploy:
      resources:
        limits:
          memory: 64M

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
      - ./www_data:/var/www/html:ro
    depends_on:
      - mqtt
    deploy:
      resources:
        limits:
          memory: 64M

  logger:
    build: ./logger
    container_name: mqtt_logger
    restart: always
    volumes:
      - ./www_data:/var/www/html # Shared folder for the JSON file
    depends_on:
      - mqtt
    deploy:
      resources:
        limits:
          memory: 64M